# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b3MdJ3_qW168fX1Rmu1hBUiIsr9l7OU-
"""

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Streamlit on Google Colab")
# st.write("Hello, World! 🚀")
# st.write("Your app is successfully running.")

!wget -qO- ://icanhazip.com

!streamlit run app.py &>/content/logs.txt &

!npx localtunnel --port 8501

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import os
# from pipeline import CandidateRankerEngine, write_submission_csv
# st.set_page_config(page_title="Redrob Talent Discoverer", layout="wide")
# 
# st.title("🛡️ Noise-Resilient Candidate Discoverer & Ranker Sandbox")
# st.subheader("Data Science Engineering Portfolio System Framework")

# Cache the heavy indexing infrastructure run to ensure UI doesn't freeze between slide adjustments
@st.cache_resource
def initialize_engine_resource(data_path):
    engine = CandidateRankerEngine()
    engine.build_indexes(data_path)
    return engine

DATA_FILE_TARGET = "sample_candidates.json.gz" # Switch to full historical dataset path as needed

if not os.path.exists(DATA_FILE_TARGET):
    st.error(f"Target data compress file '{DATA_FILE_TARGET}' not located in app workspace directory context.")
else:
    # Build or restore indexes
    with st.spinner("Streaming records and configuring vector database index matrices..."):
        engine = initialize_engine_resource(DATA_FILE_TARGET)

    # User Input Panels Configuration Layout
    st.sidebar.header("Pipeline Hyperparameters Optimization")
    lexical_w = st.sidebar.slider("BM25 Keyword Matching Weight", 0.0, 1.0, 0.3, step=0.05)
    semantic_w = st.sidebar.slider("FAISS Vector Similarity Weight", 0.0, 1.0, 0.7, step=0.05)

    st.sidebar.info("The configuration defaults give 70% preference to deep contextual intent vectors to defeat keyword stuffing traps.")

    jd_input = st.text_area(
        "Job Description Context Query Target",
        value="Senior AI Engineer Founding Team. Depth in ML systems, embeddings, ranking, retrieval pipelines. Noida/Pune hybrid location preference.",
        height=150
    )

    if st.button("Trigger Candidate Discovery Search"):
        with st.spinner("Querying vector database index and evaluating behavioral modifier vectors..."):
            results = engine.run_ranking_pipeline(jd_input, bm25_weight=lexical_w, semantic_weight=semantic_w)

            st.success(f"Processing Complete. Top 100 Talent Matrix isolated.")

            # Display metrics overview summary cards
            c1, c2 = st.columns(2)
            c1.metric("Highest Candidate Match Score", f"{results[0]['score']:.4f}")
            c2.metric("Lowest Output Bound Score (Rank 100)", f"{results[-1]['score']:.4f}")

            # Show output results inside interactive table viewer matrix UI
            st.dataframe(results, use_container_width=True)

            # Save a copy locally to test submission format validation scripts
            write_submission_csv(results, "sandbox_test_submission.csv")
