# -*- coding: utf-8 -*-
"""pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11q-XOTnO5QyL27Ss1m4kN-ivY9eTH4yN
"""

pip install pandas numpy rank_bm25 sentence-transformers faiss-cpu streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pipeline.py
# import gzip
# import json
# import csv
# import numpy as np
# from datetime import datetime
# from rank_bm25 import BM25Okapi
# import faiss
# from sentence_transformers import SentenceTransformer
#

"""STEP 1: STREAMING UTILITY"""

def stream_candidates(file_path):
    """Streams candidates line-by-line from a gzipped JSONL file to save RAM."""
    with gzip.open(file_path, 'rt', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                yield json.loads(line)

"""STEP 2: THE HONEYPOT PURGE ENGINE"""

def is_valid_profile(candidate):
    """
    Validates logical consistency of profiles to automatically drop
    impossible 'honeypot' trap candidates.
    """
    profile = candidate.get("profile", {})
    career_history = candidate.get("career_history", [])
    skills = [s.get("name", "").lower() for s in candidate.get("skills", [])]

    current_year = datetime.now().year

    # Rule 1: Tool-Age Verification vs Real-world Timelines
    modern_tools = {
        "gpt-4": 2023, "langchain": 2022, "llama 3": 2024,
        "llama-3": 2024, "pinecone": 2021, "mistral": 2023
    }

    # Calculate years of experience candidate claims with modern tools
    for skill in candidate.get("skills", []):
        name = skill.get("name", "").lower()
        duration_years = (skill.get("duration_months", 0) or 0) / 12.0

        if name in modern_tools:
            earliest_allowed_start = modern_tools[name]
            claimed_start_year = current_year - duration_years
            if claimed_start_year < earliest_allowed_start - 1: # 1 year buffer max
                return False # Impossible tool experience timeline

    # Rule 2: Title-to-Skill Core Discrepancies
    disqualified_titles = ["graphic designer", "sales executive", "content writer", "hr manager"]
    current_title = profile.get("current_title", "").lower()

    if any(dq in current_title for dq in disqualified_titles):
        # A true deep AI engineer will not have a non-technical current title
        ai_core_count = sum(1 for s in skills if any(kw in s for kw in ["ml", "nlp", "llm", "retrieval", "vector", "embedding"]))
        if ai_core_count > 5:
            return False # Clear keyword-stuffer honeypot profile

    # Rule 3: Temporal Sequence Impossibilities
    for job in career_history:
        start_date_str = job.get("start_date")
        end_date_str = job.get("end_date")
        if start_date_str and end_date_str:
            try:
                start = datetime.strptime(start_date_str, "%Y-%m-%d")
                end = datetime.strptime(end_date_str, "%Y-%m-%d")
                if start > end:
                    return False # Candidate traveling backward in time
            except ValueError:
                continue

    return True

"""STEP 3: HYBRID & FAISS VECTOR SEARCH ENGINE"""

class CandidateRankerEngine:
    def __init__(self, model_name="all-MiniLM-L6-v2"):
        self.model = SentenceTransformer(model_name)
        self.candidate_metadata = {}
        self.faiss_index = None
        self.corpus_for_bm25 = []
        self.candidate_ids_ordered = []

    def build_indexes(self, file_path):
        """Streams, purges honeypots, and builds FAISS and BM25 indexing layers."""
        embeddings_list = []

        print("Starting dataset streaming, honeypot purging, and encoding...")
        for candidate in stream_candidates(file_path):
            cid = candidate["candidate_id"]

            # Step 2 execution: Purge honeypots
            if not is_valid_profile(candidate):
                continue

            # Store metadata for final behavioral weighting stage
            self.candidate_metadata[cid] = candidate
            self.candidate_ids_ordered.append(cid)

            # Construct a rich textual context representation for embeddings and BM25
            profile = candidate.get("profile", {})
            skills_text = ", ".join([s.get("name", "") for s in candidate.get("skills", [])])
            resume_context = f"{profile.get('headline', '')} {profile.get('summary', '')} Skills: {skills_text}"

            # Prepare BM25 tokenized format
            self.corpus_for_bm25.append(resume_context.lower().split())

            # Generate local semantic vector
            vec = self.model.encode(resume_context)
            embeddings_list.append(vec)

        # Build Flat Inner Product (Cosine equivalent if vectors are normalized) FAISS Index
        embeddings_matrix = np.array(embeddings_list).astype('float32')
        faiss.normalize_L2(embeddings_matrix) # Essential for Cosine similarity matching

        self.faiss_index = faiss.IndexFlatIP(embeddings_matrix.shape[1])
        self.faiss_index.add(embeddings_matrix)
        self.bm25 = BM25Okapi(self.corpus_for_bm25)
        print(f"Indexing Complete. Successfully loaded {len(self.candidate_ids_ordered)} validated profiles.")

    def run_ranking_pipeline(self, job_description, bm25_weight=0.3, semantic_weight=0.7):
        """Executes Hybrid search, modifies with behavioral signals, and creates Top 100."""
        # 1. Compute Dense Scores using FAISS
        jd_vector = self.model.encode([job_description]).astype('float32')
        faiss.normalize_L2(jd_vector)

        # Search the index to collect semantic raw scores
        num_candidates = len(self.candidate_ids_ordered)
        faiss_scores, faiss_indices = self.faiss_index.search(jd_vector, num_candidates)

        dense_score_map = {self.candidate_ids_ordered[idx]: score for score, idx in zip(faiss_scores[0], faiss_indices[0])}

        # 2. Compute Lexical Scores using BM25
        jd_tokens = job_description.lower().split()
        bm25_raw_scores = self.bm25.get_scores(jd_tokens)
        lexical_score_map = {self.candidate_ids_ordered[i]: score for i, score in enumerate(bm25_raw_scores)}

        # 3. Apply Multiplicative Behavioral Modification Matrix
        final_candidates_pool = []
        current_date = datetime.strptime("2026-06-30", "%Y-%m-%d") # Dataset relative anchor context

        for cid in self.candidate_ids_ordered:
            candidate = self.candidate_metadata[cid]
            sig = candidate.get("redrob_signals", {})

            # Normalize components
            dense_score = float(dense_score_map.get(cid, 0.0))
            lexical_score = lexical_score_map.get(cid, 0.0) / (max(bm25_raw_scores) if max(bm25_raw_scores) > 0 else 1.0)

            base_hybrid_score = (bm25_weight * lexical_score) + (semantic_weight * dense_score)

            # Multiplier System Envelope Configuration
            multiplier = 1.0

            # Signal: Platform Inactivity
            last_active = datetime.strptime(sig.get("last_active_date", "2025-01-01"), "%Y-%m-%d")
            days_inactive = (current_date - last_active).days
            if days_inactive > 90:
                multiplier *= 0.2 # Critical penalty for cold accounts
            elif days_inactive <= 7:
                multiplier *= 1.2 # Active pipeline bonus

            # Signal: Responsiveness Depth
            response_rate = sig.get("recruiter_response_rate", 0.0)
            if response_rate < 0.20:
                multiplier *= 0.3
            elif response_rate > 0.80:
                multiplier *= 1.15

            # Signal: Notice Period Logistical Compatibility
            notice = sig.get("notice_period_days", 90)
            if notice <= 30:
                multiplier *= 1.1 # Fast onboarding incentive

            # Calculate final adjusted score
            final_score = base_hybrid_score * multiplier

            # Append candidate with their score metadata to the pool
            final_candidates_pool.append({
                "candidate_id": cid,
                "score": final_score,
                "candidate_data": candidate
            })

        # 4. Sort and Extract Top 100 Candidates (Fixes your initial sorting block error)
        sorted_pool = sorted(final_candidates_pool, key=lambda x: (-x["score"], x["candidate_id"]))
        top_100 = sorted_pool[:100]

        for rank_idx, item in enumerate(top_100, 1):
            item["rank"] = rank_idx

        return top_100

"""STEP 4: COMPLIANT SUBMISSION GENERATION & FORMAT SORTING"""

def write_submission_csv(top_100_output, output_filename="team_submission.csv"):
    """Writes strict four-column file formatted precisely to validation specs."""
    fields = ["candidate_id", "rank", "score", "reasoning"]
    with open(output_filename, mode="w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in top_100_output:
            writer.writerow({
                "candidate_id": row["candidate_id"],
                "rank": row["rank"],
                "score": round(row["score"], 4),
                "reasoning": row["reasoning"]
            })
    print(f"Compliant submission file cleanly saved to disk as: {output_filename}")
